# Generated by Django 4.1.6 on 2023-03-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='tipoDeArticulo',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.IntegerField(choices=[[0, 'Tecnologia'], [0, 'Deportes'], [0, 'Vehiculos'], [0, 'Supermercado'], [0, 'Hogar'], [0, 'Boutique']], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
