# Generated by Django 4.1.6 on 2023-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_remove_producto_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.IntegerField(choices=[[0, 'Tecnologia'], [0, 'Deportes'], [0, 'Vehiculos'], [0, 'Supermercado'], [0, 'Hogar'], [0, 'Ropa y Accesorios']]),
        ),
    ]
