# Generated by Django 4.1.6 on 2023-03-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0006_producto_delete_deportes_delete_hogar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[['Tecnologia', 'Tecnologia'], ['Deportes', 'Deportes'], ['Vehiculos', 'Vehiculos'], ['Super Mercado', 'Super Mercardo'], ['Hogar', 'Hogar'], ['Ropa & Estetica', 'Ropa & Estetica']], default='Opcion', max_length=40),
        ),
    ]
