# Generated by Django 4.1.6 on 2023-03-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0008_alter_producto_descripcion_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[['Tecnologia', 'Tecnologia'], ['Deportes', 'Deportes'], ['Vehiculos', 'Vehiculos'], ['SuperMercado', 'SuperMercardo'], ['Hogar', 'Hogar'], ['RopaEstetica', 'RopaEstetica']], default='Opcion', max_length=40),
        ),
    ]
